#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLLH
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLLH_ThayCao")]
	public partial class databaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_GiangVien(tbl_GiangVien instance);
    partial void Updatetbl_GiangVien(tbl_GiangVien instance);
    partial void Deletetbl_GiangVien(tbl_GiangVien instance);
    partial void Inserttbl_SinhVien(tbl_SinhVien instance);
    partial void Updatetbl_SinhVien(tbl_SinhVien instance);
    partial void Deletetbl_SinhVien(tbl_SinhVien instance);
    partial void Inserttbl_KhoaHoc(tbl_KhoaHoc instance);
    partial void Updatetbl_KhoaHoc(tbl_KhoaHoc instance);
    partial void Deletetbl_KhoaHoc(tbl_KhoaHoc instance);
    partial void Inserttbl_LopHoc(tbl_LopHoc instance);
    partial void Updatetbl_LopHoc(tbl_LopHoc instance);
    partial void Deletetbl_LopHoc(tbl_LopHoc instance);
    partial void Inserttbl_LopHoc_GiangVien(tbl_LopHoc_GiangVien instance);
    partial void Updatetbl_LopHoc_GiangVien(tbl_LopHoc_GiangVien instance);
    partial void Deletetbl_LopHoc_GiangVien(tbl_LopHoc_GiangVien instance);
    partial void Inserttbl_LopHoc_SinhVien(tbl_LopHoc_SinhVien instance);
    partial void Updatetbl_LopHoc_SinhVien(tbl_LopHoc_SinhVien instance);
    partial void Deletetbl_LopHoc_SinhVien(tbl_LopHoc_SinhVien instance);
    #endregion
		
		public databaseDataContext() : 
				base(global::QLLH.Properties.Settings.Default.QLLH_ThayCaoConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_GiangVien> tbl_GiangViens
		{
			get
			{
				return this.GetTable<tbl_GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SinhVien> tbl_SinhViens
		{
			get
			{
				return this.GetTable<tbl_SinhVien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_KhoaHoc> tbl_KhoaHocs
		{
			get
			{
				return this.GetTable<tbl_KhoaHoc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LopHoc> tbl_LopHocs
		{
			get
			{
				return this.GetTable<tbl_LopHoc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LopHoc_GiangVien> tbl_LopHoc_GiangViens
		{
			get
			{
				return this.GetTable<tbl_LopHoc_GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LopHoc_SinhVien> tbl_LopHoc_SinhViens
		{
			get
			{
				return this.GetTable<tbl_LopHoc_SinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_GiangVien")]
	public partial class tbl_GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGV;
		
		private string _HoTen;
		
		private string _SDT;
		
		private string _CCCD;
		
		private string _DiaChi;
		
		private EntitySet<tbl_LopHoc_GiangVien> _tbl_LopHoc_GiangViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVChanging(string value);
    partial void OnMaGVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public tbl_GiangVien()
		{
			this._tbl_LopHoc_GiangViens = new EntitySet<tbl_LopHoc_GiangVien>(new Action<tbl_LopHoc_GiangVien>(this.attach_tbl_LopHoc_GiangViens), new Action<tbl_LopHoc_GiangVien>(this.detach_tbl_LopHoc_GiangViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGV
		{
			get
			{
				return this._MaGV;
			}
			set
			{
				if ((this._MaGV != value))
				{
					this.OnMaGVChanging(value);
					this.SendPropertyChanging();
					this._MaGV = value;
					this.SendPropertyChanged("MaGV");
					this.OnMaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NVarChar(50)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_GiangVien_tbl_LopHoc_GiangVien", Storage="_tbl_LopHoc_GiangViens", ThisKey="MaGV", OtherKey="MaGV")]
		public EntitySet<tbl_LopHoc_GiangVien> tbl_LopHoc_GiangViens
		{
			get
			{
				return this._tbl_LopHoc_GiangViens;
			}
			set
			{
				this._tbl_LopHoc_GiangViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_LopHoc_GiangViens(tbl_LopHoc_GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_GiangVien = this;
		}
		
		private void detach_tbl_LopHoc_GiangViens(tbl_LopHoc_GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_GiangVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SinhVien")]
	public partial class tbl_SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MSSV;
		
		private string _HoTen;
		
		private string _LopQL;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private string _SDT;
		
		private string _Email;
		
		private EntitySet<tbl_LopHoc_SinhVien> _tbl_LopHoc_SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnLopQLChanging(string value);
    partial void OnLopQLChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public tbl_SinhVien()
		{
			this._tbl_LopHoc_SinhViens = new EntitySet<tbl_LopHoc_SinhVien>(new Action<tbl_LopHoc_SinhVien>(this.attach_tbl_LopHoc_SinhViens), new Action<tbl_LopHoc_SinhVien>(this.detach_tbl_LopHoc_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LopQL", DbType="NChar(10)")]
		public string LopQL
		{
			get
			{
				return this._LopQL;
			}
			set
			{
				if ((this._LopQL != value))
				{
					this.OnLopQLChanging(value);
					this.SendPropertyChanging();
					this._LopQL = value;
					this.SendPropertyChanged("LopQL");
					this.OnLopQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_SinhVien_tbl_LopHoc_SinhVien", Storage="_tbl_LopHoc_SinhViens", ThisKey="MSSV", OtherKey="MSSV")]
		public EntitySet<tbl_LopHoc_SinhVien> tbl_LopHoc_SinhViens
		{
			get
			{
				return this._tbl_LopHoc_SinhViens;
			}
			set
			{
				this._tbl_LopHoc_SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_LopHoc_SinhViens(tbl_LopHoc_SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_SinhVien = this;
		}
		
		private void detach_tbl_LopHoc_SinhViens(tbl_LopHoc_SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_SinhVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_KhoaHoc")]
	public partial class tbl_KhoaHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoaHoc;
		
		private string _TenKhoaHoc;
		
		private string _ThoiGian;
		
		private System.Nullable<int> _GioiHanSinhVien;
		
		private System.Nullable<int> _GioiHanGiangVien;
		
		private System.Nullable<int> _KinhPhiDongGop;
		
		private System.Nullable<int> _SoBuoiThucHanh;
		
		private System.Nullable<int> _SoBuoiLyThuyet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaHocChanging(string value);
    partial void OnMaKhoaHocChanged();
    partial void OnTenKhoaHocChanging(string value);
    partial void OnTenKhoaHocChanged();
    partial void OnThoiGianChanging(string value);
    partial void OnThoiGianChanged();
    partial void OnGioiHanSinhVienChanging(System.Nullable<int> value);
    partial void OnGioiHanSinhVienChanged();
    partial void OnGioiHanGiangVienChanging(System.Nullable<int> value);
    partial void OnGioiHanGiangVienChanged();
    partial void OnKinhPhiDongGopChanging(System.Nullable<int> value);
    partial void OnKinhPhiDongGopChanged();
    partial void OnSoBuoiThucHanhChanging(System.Nullable<int> value);
    partial void OnSoBuoiThucHanhChanged();
    partial void OnSoBuoiLyThuyetChanging(System.Nullable<int> value);
    partial void OnSoBuoiLyThuyetChanged();
    #endregion
		
		public tbl_KhoaHoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaHoc", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoaHoc
		{
			get
			{
				return this._MaKhoaHoc;
			}
			set
			{
				if ((this._MaKhoaHoc != value))
				{
					this.OnMaKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaHoc = value;
					this.SendPropertyChanged("MaKhoaHoc");
					this.OnMaKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoaHoc", DbType="NChar(50)")]
		public string TenKhoaHoc
		{
			get
			{
				return this._TenKhoaHoc;
			}
			set
			{
				if ((this._TenKhoaHoc != value))
				{
					this.OnTenKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._TenKhoaHoc = value;
					this.SendPropertyChanged("TenKhoaHoc");
					this.OnTenKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="NVarChar(50)")]
		public string ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiHanSinhVien", DbType="Int")]
		public System.Nullable<int> GioiHanSinhVien
		{
			get
			{
				return this._GioiHanSinhVien;
			}
			set
			{
				if ((this._GioiHanSinhVien != value))
				{
					this.OnGioiHanSinhVienChanging(value);
					this.SendPropertyChanging();
					this._GioiHanSinhVien = value;
					this.SendPropertyChanged("GioiHanSinhVien");
					this.OnGioiHanSinhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiHanGiangVien", DbType="Int")]
		public System.Nullable<int> GioiHanGiangVien
		{
			get
			{
				return this._GioiHanGiangVien;
			}
			set
			{
				if ((this._GioiHanGiangVien != value))
				{
					this.OnGioiHanGiangVienChanging(value);
					this.SendPropertyChanging();
					this._GioiHanGiangVien = value;
					this.SendPropertyChanged("GioiHanGiangVien");
					this.OnGioiHanGiangVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinhPhiDongGop", DbType="Int")]
		public System.Nullable<int> KinhPhiDongGop
		{
			get
			{
				return this._KinhPhiDongGop;
			}
			set
			{
				if ((this._KinhPhiDongGop != value))
				{
					this.OnKinhPhiDongGopChanging(value);
					this.SendPropertyChanging();
					this._KinhPhiDongGop = value;
					this.SendPropertyChanged("KinhPhiDongGop");
					this.OnKinhPhiDongGopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoiThucHanh", DbType="Int")]
		public System.Nullable<int> SoBuoiThucHanh
		{
			get
			{
				return this._SoBuoiThucHanh;
			}
			set
			{
				if ((this._SoBuoiThucHanh != value))
				{
					this.OnSoBuoiThucHanhChanging(value);
					this.SendPropertyChanging();
					this._SoBuoiThucHanh = value;
					this.SendPropertyChanged("SoBuoiThucHanh");
					this.OnSoBuoiThucHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoiLyThuyet", DbType="Int")]
		public System.Nullable<int> SoBuoiLyThuyet
		{
			get
			{
				return this._SoBuoiLyThuyet;
			}
			set
			{
				if ((this._SoBuoiLyThuyet != value))
				{
					this.OnSoBuoiLyThuyetChanging(value);
					this.SendPropertyChanging();
					this._SoBuoiLyThuyet = value;
					this.SendPropertyChanged("SoBuoiLyThuyet");
					this.OnSoBuoiLyThuyetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LopHoc")]
	public partial class tbl_LopHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLH;
		
		private string _TenLH;
		
		private System.Nullable<System.DateTime> _ThoiGianBatDau;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThuc;
		
		private string _MaKhoaHoc;
		
		private EntitySet<tbl_LopHoc_GiangVien> _tbl_LopHoc_GiangViens;
		
		private EntitySet<tbl_LopHoc_SinhVien> _tbl_LopHoc_SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLHChanging(string value);
    partial void OnMaLHChanged();
    partial void OnTenLHChanging(string value);
    partial void OnTenLHChanged();
    partial void OnThoiGianBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucChanged();
    partial void OnMaKhoaHocChanging(string value);
    partial void OnMaKhoaHocChanged();
    #endregion
		
		public tbl_LopHoc()
		{
			this._tbl_LopHoc_GiangViens = new EntitySet<tbl_LopHoc_GiangVien>(new Action<tbl_LopHoc_GiangVien>(this.attach_tbl_LopHoc_GiangViens), new Action<tbl_LopHoc_GiangVien>(this.detach_tbl_LopHoc_GiangViens));
			this._tbl_LopHoc_SinhViens = new EntitySet<tbl_LopHoc_SinhVien>(new Action<tbl_LopHoc_SinhVien>(this.attach_tbl_LopHoc_SinhViens), new Action<tbl_LopHoc_SinhVien>(this.detach_tbl_LopHoc_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLH
		{
			get
			{
				return this._MaLH;
			}
			set
			{
				if ((this._MaLH != value))
				{
					this.OnMaLHChanging(value);
					this.SendPropertyChanging();
					this._MaLH = value;
					this.SendPropertyChanged("MaLH");
					this.OnMaLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLH", DbType="NChar(10)")]
		public string TenLH
		{
			get
			{
				return this._TenLH;
			}
			set
			{
				if ((this._TenLH != value))
				{
					this.OnTenLHChanging(value);
					this.SendPropertyChanging();
					this._TenLH = value;
					this.SendPropertyChanged("TenLH");
					this.OnTenLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaHoc", DbType="NChar(10)")]
		public string MaKhoaHoc
		{
			get
			{
				return this._MaKhoaHoc;
			}
			set
			{
				if ((this._MaKhoaHoc != value))
				{
					this.OnMaKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaHoc = value;
					this.SendPropertyChanged("MaKhoaHoc");
					this.OnMaKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LopHoc_tbl_LopHoc_GiangVien", Storage="_tbl_LopHoc_GiangViens", ThisKey="MaLH", OtherKey="MaLH")]
		public EntitySet<tbl_LopHoc_GiangVien> tbl_LopHoc_GiangViens
		{
			get
			{
				return this._tbl_LopHoc_GiangViens;
			}
			set
			{
				this._tbl_LopHoc_GiangViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LopHoc_tbl_LopHoc_SinhVien", Storage="_tbl_LopHoc_SinhViens", ThisKey="MaLH", OtherKey="MaLH")]
		public EntitySet<tbl_LopHoc_SinhVien> tbl_LopHoc_SinhViens
		{
			get
			{
				return this._tbl_LopHoc_SinhViens;
			}
			set
			{
				this._tbl_LopHoc_SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_LopHoc_GiangViens(tbl_LopHoc_GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LopHoc = this;
		}
		
		private void detach_tbl_LopHoc_GiangViens(tbl_LopHoc_GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LopHoc = null;
		}
		
		private void attach_tbl_LopHoc_SinhViens(tbl_LopHoc_SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LopHoc = this;
		}
		
		private void detach_tbl_LopHoc_SinhViens(tbl_LopHoc_SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LopHoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LopHoc_GiangVien")]
	public partial class tbl_LopHoc_GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _MaLH;
		
		private string _MaGV;
		
		private EntityRef<tbl_GiangVien> _tbl_GiangVien;
		
		private EntityRef<tbl_LopHoc> _tbl_LopHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnMaLHChanging(string value);
    partial void OnMaLHChanged();
    partial void OnMaGVChanging(string value);
    partial void OnMaGVChanged();
    #endregion
		
		public tbl_LopHoc_GiangVien()
		{
			this._tbl_GiangVien = default(EntityRef<tbl_GiangVien>);
			this._tbl_LopHoc = default(EntityRef<tbl_LopHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLH", DbType="NChar(10)")]
		public string MaLH
		{
			get
			{
				return this._MaLH;
			}
			set
			{
				if ((this._MaLH != value))
				{
					if (this._tbl_LopHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLHChanging(value);
					this.SendPropertyChanging();
					this._MaLH = value;
					this.SendPropertyChanged("MaLH");
					this.OnMaLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGV", DbType="NChar(10)")]
		public string MaGV
		{
			get
			{
				return this._MaGV;
			}
			set
			{
				if ((this._MaGV != value))
				{
					if (this._tbl_GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGVChanging(value);
					this.SendPropertyChanging();
					this._MaGV = value;
					this.SendPropertyChanged("MaGV");
					this.OnMaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_GiangVien_tbl_LopHoc_GiangVien", Storage="_tbl_GiangVien", ThisKey="MaGV", OtherKey="MaGV", IsForeignKey=true)]
		public tbl_GiangVien tbl_GiangVien
		{
			get
			{
				return this._tbl_GiangVien.Entity;
			}
			set
			{
				tbl_GiangVien previousValue = this._tbl_GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._tbl_GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_GiangVien.Entity = null;
						previousValue.tbl_LopHoc_GiangViens.Remove(this);
					}
					this._tbl_GiangVien.Entity = value;
					if ((value != null))
					{
						value.tbl_LopHoc_GiangViens.Add(this);
						this._MaGV = value.MaGV;
					}
					else
					{
						this._MaGV = default(string);
					}
					this.SendPropertyChanged("tbl_GiangVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LopHoc_tbl_LopHoc_GiangVien", Storage="_tbl_LopHoc", ThisKey="MaLH", OtherKey="MaLH", IsForeignKey=true)]
		public tbl_LopHoc tbl_LopHoc
		{
			get
			{
				return this._tbl_LopHoc.Entity;
			}
			set
			{
				tbl_LopHoc previousValue = this._tbl_LopHoc.Entity;
				if (((previousValue != value) 
							|| (this._tbl_LopHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_LopHoc.Entity = null;
						previousValue.tbl_LopHoc_GiangViens.Remove(this);
					}
					this._tbl_LopHoc.Entity = value;
					if ((value != null))
					{
						value.tbl_LopHoc_GiangViens.Add(this);
						this._MaLH = value.MaLH;
					}
					else
					{
						this._MaLH = default(string);
					}
					this.SendPropertyChanged("tbl_LopHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LopHoc_SinhVien")]
	public partial class tbl_LopHoc_SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _MaLH;
		
		private string _MSSV;
		
		private EntityRef<tbl_LopHoc> _tbl_LopHoc;
		
		private EntityRef<tbl_SinhVien> _tbl_SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnMaLHChanging(string value);
    partial void OnMaLHChanged();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    #endregion
		
		public tbl_LopHoc_SinhVien()
		{
			this._tbl_LopHoc = default(EntityRef<tbl_LopHoc>);
			this._tbl_SinhVien = default(EntityRef<tbl_SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLH", DbType="NChar(10)")]
		public string MaLH
		{
			get
			{
				return this._MaLH;
			}
			set
			{
				if ((this._MaLH != value))
				{
					if (this._tbl_LopHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLHChanging(value);
					this.SendPropertyChanging();
					this._MaLH = value;
					this.SendPropertyChanged("MaLH");
					this.OnMaLHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="NChar(10)")]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					if (this._tbl_SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LopHoc_tbl_LopHoc_SinhVien", Storage="_tbl_LopHoc", ThisKey="MaLH", OtherKey="MaLH", IsForeignKey=true)]
		public tbl_LopHoc tbl_LopHoc
		{
			get
			{
				return this._tbl_LopHoc.Entity;
			}
			set
			{
				tbl_LopHoc previousValue = this._tbl_LopHoc.Entity;
				if (((previousValue != value) 
							|| (this._tbl_LopHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_LopHoc.Entity = null;
						previousValue.tbl_LopHoc_SinhViens.Remove(this);
					}
					this._tbl_LopHoc.Entity = value;
					if ((value != null))
					{
						value.tbl_LopHoc_SinhViens.Add(this);
						this._MaLH = value.MaLH;
					}
					else
					{
						this._MaLH = default(string);
					}
					this.SendPropertyChanged("tbl_LopHoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_SinhVien_tbl_LopHoc_SinhVien", Storage="_tbl_SinhVien", ThisKey="MSSV", OtherKey="MSSV", IsForeignKey=true)]
		public tbl_SinhVien tbl_SinhVien
		{
			get
			{
				return this._tbl_SinhVien.Entity;
			}
			set
			{
				tbl_SinhVien previousValue = this._tbl_SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._tbl_SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_SinhVien.Entity = null;
						previousValue.tbl_LopHoc_SinhViens.Remove(this);
					}
					this._tbl_SinhVien.Entity = value;
					if ((value != null))
					{
						value.tbl_LopHoc_SinhViens.Add(this);
						this._MSSV = value.MSSV;
					}
					else
					{
						this._MSSV = default(string);
					}
					this.SendPropertyChanged("tbl_SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
