<?xml version="1.0" encoding="utf-8"?><Database Name="QLLH_ThayCao" Class="databaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-827727I\SQLEXPRESS;Initial Catalog=QLLH_ThayCao;User ID=sasa" SettingsObjectName="QLLH.Properties.Settings" SettingsPropertyName="QLLH_ThayCaoConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_GiangVien" Member="tbl_GiangViens">
    <Type Name="tbl_GiangVien">
      <Column Name="MaGV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbl_GiangVien_tbl_LopHoc_GiangVien" Member="tbl_LopHoc_GiangViens" ThisKey="MaGV" OtherKey="MaGV" Type="tbl_LopHoc_GiangVien" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SinhVien" Member="tbl_SinhViens">
    <Type Name="tbl_SinhVien">
      <Column Name="MSSV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LopQL" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Association Name="tbl_SinhVien_tbl_LopHoc_SinhVien" Member="tbl_LopHoc_SinhViens" ThisKey="MSSV" OtherKey="MSSV" Type="tbl_LopHoc_SinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_KhoaHoc" Member="tbl_KhoaHocs">
    <Type Name="tbl_KhoaHoc">
      <Column Name="MaKhoaHoc" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoaHoc" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="ThoiGian" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiHanSinhVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GioiHanGiangVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KinhPhiDongGop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoBuoiThucHanh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoBuoiLyThuyet" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_LopHoc" Member="tbl_LopHocs">
    <Type Name="tbl_LopHoc">
      <Column Name="MaLH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLH" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ThoiGianBatDau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiGianKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="tbl_LopHoc_tbl_LopHoc_GiangVien" Member="tbl_LopHoc_GiangViens" ThisKey="MaLH" OtherKey="MaLH" Type="tbl_LopHoc_GiangVien" />
      <Association Name="tbl_LopHoc_tbl_LopHoc_SinhVien" Member="tbl_LopHoc_SinhViens" ThisKey="MaLH" OtherKey="MaLH" Type="tbl_LopHoc_SinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_LopHoc_GiangVien" Member="tbl_LopHoc_GiangViens">
    <Type Name="tbl_LopHoc_GiangVien">
      <Column Name="Id" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLH" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaGV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="tbl_GiangVien_tbl_LopHoc_GiangVien" Member="tbl_GiangVien" ThisKey="MaGV" OtherKey="MaGV" Type="tbl_GiangVien" IsForeignKey="true" />
      <Association Name="tbl_LopHoc_tbl_LopHoc_GiangVien" Member="tbl_LopHoc" ThisKey="MaLH" OtherKey="MaLH" Type="tbl_LopHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_LopHoc_SinhVien" Member="tbl_LopHoc_SinhViens">
    <Type Name="tbl_LopHoc_SinhVien">
      <Column Name="Id" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLH" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MSSV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="tbl_LopHoc_tbl_LopHoc_SinhVien" Member="tbl_LopHoc" ThisKey="MaLH" OtherKey="MaLH" Type="tbl_LopHoc" IsForeignKey="true" />
      <Association Name="tbl_SinhVien_tbl_LopHoc_SinhVien" Member="tbl_SinhVien" ThisKey="MSSV" OtherKey="MSSV" Type="tbl_SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>